name: tv_shows
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  flutter_rating_bar: ^4.0.0
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  dio: ^4.0.4
  freezed_annotation:
  flutter_secure_storage:
  hive:
  hive_flutter:
  image_picker: ^0.8.5
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  freezed:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  hive_generator:
  mockito:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/images/
    - assets/images/shows/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: 'assets/icons/app-icon.jpg'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#3D1D72'
  image: assets/splash.png # nisam uspio skontat kako da exportam samo ona dva elementa zajedno, bez backgrounda, pa sam ga samo ostavio ovako
